services:
  db:
    image: postgres:latest
    container_name: user-authentication-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: user-authentication-api
    env_file:
      - .env
    ports:
      - "8000:8080"
    depends_on:
      - db

volumes:
  postgres: